// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.IntroWebApi.Database;

#nullable disable

namespace _1.IntroWebApi.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    [Migration("20240729182942_AddedAccountsTable")]
    partial class AddedAccountsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_1.IntroWebApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("52af4914-a8f7-4650-bc5b-837da60095ae"),
                            City = "New York",
                            CreationDateTime = new DateTime(2024, 7, 29, 18, 29, 41, 985, DateTimeKind.Utc).AddTicks(280),
                            Email = "johndoe@example.com",
                            UserName = "JohnDoe"
                        },
                        new
                        {
                            Id = new Guid("4a828e82-e582-490c-b519-5c5848c7e9ce"),
                            City = "Los Angeles",
                            CreationDateTime = new DateTime(2024, 7, 29, 18, 29, 41, 985, DateTimeKind.Utc).AddTicks(295),
                            Email = "johnnotdoe@notexample.notcom",
                            UserName = "JohnNotDoe"
                        });
                });

            modelBuilder.Entity("_1._IntroWebApi.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
