// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.IntroWebApi.Database;

#nullable disable

namespace _1.IntroWebApi.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    partial class FoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_1.IntroWebApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d71ffcd9-1e83-424b-b328-2d22d690f584"),
                            City = "New York",
                            CreationDateTime = new DateTime(2024, 7, 16, 16, 28, 39, 401, DateTimeKind.Utc).AddTicks(5913),
                            Email = "johndoe@example.com",
                            UserName = "JohnDoe"
                        },
                        new
                        {
                            Id = new Guid("7d29a601-31d2-42de-a5ec-c56b025f0c81"),
                            City = "Los Angeles",
                            CreationDateTime = new DateTime(2024, 7, 16, 16, 28, 39, 401, DateTimeKind.Utc).AddTicks(5921),
                            Email = "johnnotdoe@notexample.notcom",
                            UserName = "JohnNotDoe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
